image:
  name: artifactory.tools.in.pan-net.eu/docker.io/goreleaser/goreleaser
  entrypoint: ['']

variables:
  GOPATH: $CI_PROJECT_DIR/build
  GOCACHE: $CI_PROJECT_DIR/build/cache

cache:
  paths:
    - build/

before_script:
  - mkdir -p $CI_PROJECT_DIR/build/pkg $CI_PROJECT_DIR/build/cache $CI_PROJECT_DIR/build/bin
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tools.in.pan-net.eu/".insteadOf https://gitlab.tools.in.pan-net.eu/
  - go env -w GOPRIVATE=gitlab.tools.in.pan-net.eu

stages:
  - release

release:
  stage: release
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - goreleaser release --rm-dist --skip-sign
